spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://106.52.210.60:3306/homework?serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: root
    password: l&73ROjjLY
